DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS attendees;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  ingredients TEXT NOT NULL,
  instructions TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE bookings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  date_booking TEXT NOT NULL,
  author_id INTEGER NOT NULL,
  attendees_count INTEGER NOT NULL,
  max_capacity INTEGER NOT NULL,
  description TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id) 
);

CREATE TABLE attendees (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  booking_id INTEGER NOT NULL,
  date_booked TEXT NOT NULL,
  FOREIGN KEY (booking_id) REFERENCES booking (id)
)